# This workflow runs tests on pull requests.
name: tests

on:
  pull_request:
  push:

jobs:
  command-matrix:
    strategy:
    matrix:
      build-version: ["16.04", "18.04", "20.04"]
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup fake ssh key
        run: echo "dummyssh" > dummy_id_rsa.pub
      - name: Install dependencies 
        run: |
          sudo apt update
          sudo apt-get install dos2unix p7zip-full cpio gzip genisoimage whois pwgen wget fakeroot isolinux xorriso qemu-utils qemu-kvm
      - name: Build iso image
        run: ./ubuntu/${{ matrix.category }}/build-iso.sh dummy_id_rsa.pub
